### ISSUE TITLE
Scary usage of sudo

### ISSUE THREAD

**Issue by thesharp** [klem4/SSH-keeper#1]
During the installation process `sudo` looks really scary. The tool itself looks like it belongs inside `$HOME/bin` and shouldn't require root privileges for a default installation.

ps: `clean` target should never remove the software. It should be used as to clean compiled binaries inside the compile directory. You should use `uninstall` there.

**Comment by klem4** [comment]
@thesharp thx for comment, bro)) i think it's fixed for now.

**Comment by thesharp** [comment]
Well, it's semi-fixed. :)

It will work flawlessly on OSX with Homebrew installed, because in that case `/usr/local` will be chowned to the current user. In Linux it will fail, because it will be chowned to root. Consider using `$HOME/bin`, because it almost always is inside users' `$PATH`.

**Comment by klem4** [comment]
@thesharp
For example, on my `ubuntu 14.04`, there is not `$HOME/bin` in `$PATH` by default. 
Is this normal if i'll modify `.basrc` users file with adding `export PATH=$PATH:~/bin/` ?

**Comment by thesharp** [comment]
Yeah, that's a perfectly valid line.

ps: Strange that Ubuntu doesn't have `$PATH/bin` in it's default `.bashrc`.
Maybe that was just a RedHat thing.

**Comment by klem4** [comment]
fixed in https://github.com/klem4/SSH-keeper/commit/387255cf79a9618216d8be074c877cdc51fae9ca and https://github.com/klem4/SSH-keeper/commit/723976661dffb600b07e83180d9967949797562e i hope) 
But I think it would be wise to check for /home/bin in $PATH before appending RC file.
